# numpy

## 导入库


In [1]:
import numpy as np

In [2]:
a=[1,2,3,4]
a+1

TypeError: can only concatenate list (not "int") to list

In [3]:
[x+1 for x in a]

[2, 3, 4, 5]

In [4]:
b=[2,3,4,5]
a+b

[1, 2, 3, 4, 2, 3, 4, 5]

In [5]:
[x+y for (x,y) in zip(a,b)]

[3, 5, 7, 9]

## array函数

In [6]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a+1

array([2, 3, 4, 5])

In [8]:
a*2

array([2, 4, 6, 8])

In [9]:
b=np.array([2,3,4,5])
a+b

array([3, 5, 7, 9])

从列表产生数组

In [10]:
l=[0,1,2,3]
a=np.array(l)
a

array([0, 1, 2, 3])

从列表传入

In [11]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

生成全0数组

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

生成全1数组

In [13]:
np.ones(5,dtype='bool')

array([ True,  True,  True,  True,  True])

使用fill方法将数组设为指定值

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.fill(2.5)
a

array([2, 2, 2, 2])

In [16]:
a=a.astype('float')
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

生成整数序列

In [17]:
a=np.arange(1,10,3)
a

array([1, 4, 7])

生成等差数列

In [18]:
a=np.linspace(1,10,21)
a

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

生成随机数

In [19]:
np.random.rand(10)

array([0.48370087, 0.53331694, 0.1825699 , 0.79658944, 0.90883082,
       0.23281901, 0.29774514, 0.78465573, 0.20057051, 0.30942703])

In [20]:
np.random.randn(10) #正态分布

array([-0.41996483, -1.71052074,  0.1898574 , -0.66228669,  1.28915811,
        0.24695046,  0.05987802, -0.14128066, -1.96184895, -0.19084141])

## array属性 

In [21]:
a

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [22]:
type(a) #查看数组的数据类型

numpy.ndarray

In [23]:
a.dtype  #查看数组中元素的数据类型

dtype('float64')

In [24]:
a.shape #返回元组，每个元素代表这一维的元素数目

(21,)

In [25]:
a.size #查看元素的数目

21

In [26]:
a.ndim #查看维度

1

## 索引和切片

In [27]:
a=np.array([0,1,2,3])
a[0]

0

In [28]:
a[0]=10
a

array([10,  1,  2,  3])

In [29]:
a=np.array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [30]:
a[1:-2]

array([12, 13])

In [31]:
a[::2]  #间隔为2取数

array([11, 13, 15])

记录电影累计票房

In [32]:
ob=np.array([21000,21800,22240,23450,25000])
ob

array([21000, 21800, 22240, 23450, 25000])

In [33]:
ob2=ob[1:]-ob[:-1]
ob2

array([ 800,  440, 1210, 1550])

## 多维array

In [36]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [37]:
a.shape

(2, 4)

In [38]:
a.size

8

In [39]:
a.ndim

2

In [40]:
a[1,3] #第1行，第3列（注意开始是从0开始）

13

In [41]:
a[1,3]=-1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [42]:
a[1]

array([10, 11, 12, -1])

In [43]:
a[:,1]

array([ 1, 11])

In [44]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [45]:
a[0,3:5]    #取第0行的“3与4”

array([3, 4])

In [46]:
a[4:,4:]   #取最后两行的最后两列

array([[44, 45],
       [54, 55]])

In [47]:
a[:,2]  #取第3列

array([ 2, 12, 22, 32, 42, 52])

In [48]:
a[2::2,::2]  #取出第2、4行的奇数列（0为第1）   [lower:upper:step]

array([[20, 22, 24],
       [40, 42, 44]])

## 切片是引用

In [50]:
a=np.array([0,1,2,3,4])
b=a[2:4]
print(b)

[2 3]


In [51]:
b[0]=10       #数组切片使用的引用机制，不会为b分配新的空间，只是让b指向了a所分配的内存空间，因此改变了b就改变了a
a             #该现象在list中不会出现

array([ 0,  1, 10,  3,  4])

In [53]:
a=[0,1,2,3,4]
b=a[2:4]
print(b)

[2, 3]


In [54]:
b[0]=10
print(a)     #切片引用现象在list中不会出现

[0, 1, 2, 3, 4]


In [55]:
a=np.array([0,1,2,3,4])
b=a[2:4].copy()         #copy函数可以显示为b分配内存，这样就不会改变a的值
b[0]=10
a

array([0, 1, 2, 3, 4])

## 花式索引是复制

In [56]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
index=[1,2,-3]
y=a[index]
print(y)

[10 20 70]


In [58]:
mask=np.array([0,2,2,0,0,1,0,0,1,0],dtype=bool)
mask

array([False,  True,  True, False, False,  True, False, False,  True,
       False])

In [59]:
a[mask]

array([10, 20, 50, 80])

二维fancy slicing

In [60]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [61]:
a[(0,1,2,3,4),(1,2,3,4,5)]   #返回次对角线的5个值

array([ 1, 12, 23, 34, 45])

In [62]:
a[3:,(0,2,4)]       #返回最后三行的0，2，4行

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [63]:
y=a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [65]:
con=np.array([0,1,1,0,1,0],dtype=bool)
a[con]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

 where语句 where(array) 会返回所有非零元素的索引

In [66]:
a=np.array([0,12,5,20])
a>10

array([False,  True, False,  True])

In [67]:
np.where(a>10)      #默认返回的是索引位置，是元组

(array([1, 3], dtype=int64),)

In [68]:
a[a>10]

array([12, 20])

In [69]:
a[np.where(a>10)]   #返回数组的元素

array([12, 20])

In [70]:
a=np.array([1,5,-3],dtype=float)
a

array([ 1.,  5., -3.])

In [71]:
a=np.array([1,2,3])                #转换类型
np.asarray(a,dtype=float)

array([1., 2., 3.])

In [74]:
a=np.array([1,2,3])
b=a.astype(float)
b

array([1., 2., 3.])

In [75]:
a                #astype未改变原数组的值，仅仅是复制

array([1, 2, 3])

In [76]:
b

array([1., 2., 3.])

## 数组操作