In [1]:
import pandas as pd
import numpy as np
from numpy import linalg as la

In [2]:
b = np.array([[1,2,3,4],[2,3,5,6],[3,5,7,9],[5,6,8,10]])
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  5,  6],
       [ 3,  5,  7,  9],
       [ 5,  6,  8, 10]])

In [3]:
c1=np.array([[2,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])  #double column 1
c1

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [4]:
c2=np.array([[0,0,0,1],[0,1,0,0],[0,0,1,0],[1,0,0,0]]) #interchange columns 1 and 4
c2

array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [5]:
c3=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,1],[0,0,0,0]]) #replace column 4 by column 3
c3

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 0]])

In [6]:
c4=np.array([[0,0,0],[1,0,0],[0,1,0],[0,0,1]])  #delete column 1
c4

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
a1=np.array([[1,0,0,0],[0,1,0,0],[0,0,1/2,0],[0,0,0,1]])   #halve row 2
a1

array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 1. ]])

In [8]:
a2=np.array([[1,0,1,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])  #add row 3 to row 1
a2

array([[1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
a3=np.array([[1,-1,0,0],[0,1,0,0],[0,-1,1,0],[0,-1,0,1]])  #subtract row 2 form each of the other row
a3

array([[ 1, -1,  0,  0],
       [ 0,  1,  0,  0],
       [ 0, -1,  1,  0],
       [ 0, -1,  0,  1]])

In [10]:
q=np.linalg.multi_dot([a3,a2,a1,b,c1,c2,c3,c4])
q

array([[ 1.5,  1.5,  1.5],
       [ 3. ,  5. ,  5. ],
       [-0.5, -1.5, -1.5],
       [ 3. ,  3. ,  3. ]])

In [11]:
a=np.linalg.multi_dot([a3,a2,a1])
a

array([[ 1. , -1. ,  0.5,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. , -1. ,  0.5,  0. ],
       [ 0. , -1. ,  0. ,  1. ]])

In [12]:
c=np.linalg.multi_dot([c1,c2,c3,c4])
c

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 1],
       [0, 0, 0]])

In [13]:
q=np.dot(np.dot(a,b),c)
q

array([[ 1.5,  1.5,  1.5],
       [ 3. ,  5. ,  5. ],
       [-0.5, -1.5, -1.5],
       [ 3. ,  3. ,  3. ]])

In [14]:
qt=np.transpose(q)
qt

array([[ 1.5,  3. , -0.5,  3. ],
       [ 1.5,  5. , -1.5,  3. ],
       [ 1.5,  5. , -1.5,  3. ]])

In [15]:
bv=np.linalg.inv(b)
bv

array([[ 2.00000000e+00,  1.77635684e-16, -2.00000000e+00,
         1.00000000e+00],
       [-5.00000000e+00, -1.00000000e+00,  4.00000000e+00,
        -1.00000000e+00],
       [-5.00000000e+00,  2.00000000e+00,  2.00000000e+00,
        -1.00000000e+00],
       [ 6.00000000e+00, -1.00000000e+00, -3.00000000e+00,
         1.00000000e+00]])

In [17]:
U,sigma,Vt=la.svd(b)

In [18]:
U

array([[-0.24579058, -0.42608073, -0.21064546, -0.84479033],
       [-0.38726604, -0.37505243,  0.83707234,  0.09311597],
       [-0.57730907, -0.40543074, -0.50415805,  0.49816143],
       [-0.67551924,  0.71653109,  0.02762318, -0.17173791]])

In [19]:
sigma

array([22.16042382,  1.327638  ,  0.38082491,  0.08925179])

In [20]:
Vt

array([[-0.27661231, -0.38776515, -0.5468767 , -0.68851267],
       [ 0.89646247,  0.22198377, -0.19528726, -0.3300623 ],
       [ 0.23407342, -0.6961862 ,  0.6441397 , -0.21358479],
       [-0.2550496 ,  0.56185956,  0.49786827, -0.60941834]])

In [32]:
x=la.multi_dot([U,np.diag(sigma),Vt])
x

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  5.,  6.],
       [ 3.,  5.,  7.,  9.],
       [ 5.,  6.,  8., 10.]])